# Database settings.
database:

  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password:

  # the JDBC URL
  url: jdbc:h2:file:C:/temp/test
  
  properties:
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate.hbm2ddl.auto: create
        hibernate.generate_statistics: true
        hibernate.show_sql: true
        hibernate.format_sql: true